services:
  postgres-docker:
    container_name: postgre-docker
    image: postgres:12.10
    environment:
      POSTGRES_DB: dbshop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"
    networks:
      - app-network
  spring-boot-docker:
    container_name: sprigboot-demoshop
    depends_on:
      - postgres-docker
    environment:
      - DATABASE_HOST=postgre-docker
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge